"""
supervised_train.py
Behavioral Cloning — SNN Satellite Controller
Trains SpikingSatelliteController to imitate a PID reference controller.

Dataset format (generated by generate_dataset.m):
  Data/
    ep_0001_events.mat  → events_matrix (T, H, W, 2) uint8 — HDF5 / v7.3
                          H = 256,  W = 512  (sensor resolution from Simulation.m)
    ep_0001_states.mat  → torque_pid (T, 3) float32 — MAT v7
                          omega_sim  (T, 3) float32 — MAT v7
    dataset_stats.npz   → normalisation stats (generated by compute_dataset_stats.py)
"""

import os
import glob
import numpy as np
import h5py
import scipy.io
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from snn_controller import SpikingSatelliteController

# =============================================================================
# CONFIGURATION
# =============================================================================
CONFIG = {
    'data_dir':      '../Data',
    'weights_dir':   '../SNN/Weights',
    'seq_length':    128,
    'batch_size':    8,
    'epochs':        200,
    'lr':            2e-5,
    'weight_decay':  1e-4,
    'val_split':     0.15,
    'grad_clip':     5.0,
    'patience':      50,
    'num_workers':   0,
    'num_steps':     4,
    'hidden_gru':    128,
    'input_size':    64,   # square downsample target; H and W are scaled independently
    'd_shift':       2,    # Desplazamiento de los datos para compensar el retraso
    're-train':      1,    # 1 Si partimos de un modelo preentrenado; 0 para nuevo modelo
}
# =============================================================================


def load_stats(data_dir: str) -> dict:
    stats_path = os.path.join(data_dir, 'dataset_stats.npz')
    if not os.path.exists(stats_path):
        raise FileNotFoundError(
            f"No se encontró '{stats_path}'.\n"
            f"Ejecuta primero: python3 compute_dataset_stats.py"
        )
    s = np.load(stats_path)
    return {k: s[k].astype(np.float32) for k in s.files}


class EpisodeDataset(Dataset):
    def __init__(self, episode_pairs: list, input_size: int, stats: dict):
        self.pairs      = episode_pairs
        self.input_size = input_size
        self.stats      = stats

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        ev_path, st_path = self.pairs[idx]

        # Cargar el episodio completo
        with h5py.File(ev_path, 'r') as f:
            events = np.array(f['events_matrix'][()], dtype=np.float32)

        # Transposición física correcta: (T, C, H, W)
        events = np.transpose(events, (0, 3, 2, 1))

        # Reducción de resolución
        T_len, C, H, W = events.shape
        if H != self.input_size or W != self.input_size:
            t = torch.from_numpy(events).reshape(T_len * C, 1, H, W)
            t = F.interpolate(t, size=(self.input_size, self.input_size), mode='area')
            events = t.reshape(T_len, C, self.input_size, self.input_size).numpy()

        # Cargar estados
        st_data = scipy.io.loadmat(st_path)
        torques = st_data['torque_pid'].astype(np.float32)

        torques = torques - self.stats['torque_mean']
        torques = torques / self.stats['torque_peak']

        return torch.from_numpy(events), torch.from_numpy(torques)


def build_dataloaders(cfg: dict, stats: dict):
    all_events = sorted(glob.glob(os.path.join(cfg['data_dir'], 'ep_*_events.mat')))
    if not all_events: raise FileNotFoundError("No episode files found.")

    pairs = []
    for ev in all_events:
        st = ev.replace('_events.mat', '_states.mat')
        if os.path.exists(st): pairs.append((ev, st))

    np.random.shuffle(pairs)
    n_val       = max(1, int(len(pairs) * cfg['val_split']))
    pairs_val   = pairs[:n_val]
    pairs_train = pairs[n_val:]

    print(f"\nDataset split: {len(pairs_train)} train / {len(pairs_val)} val episodes")

    # Ya no pasamos seq_length aquí
    ds_train = EpisodeDataset(pairs_train, cfg['input_size'], stats)
    ds_val   = EpisodeDataset(pairs_val,   cfg['input_size'], stats)

    dl_train = DataLoader(ds_train, batch_size=cfg['batch_size'],
                          shuffle=True,  drop_last=True,  num_workers=cfg['num_workers'])
    dl_val   = DataLoader(ds_val,   batch_size=cfg['batch_size'],
                          shuffle=False, drop_last=False, num_workers=cfg['num_workers'])
    return dl_train, dl_val
"""
def build_dataloaders(cfg: dict, stats: dict):
    # En lugar de buscar todos, forzamos solo el episodio 1
    ep_1_events = os.path.join(cfg['data_dir'], 'ep_0001_events.mat')
    ep_1_states = os.path.join(cfg['data_dir'], 'ep_0001_states.mat')
    
    if not os.path.exists(ep_1_events): 
        raise FileNotFoundError("¡No encuentro el episodio 0001!")

    # Creamos una lista con un solo par
    pairs = [(ep_1_events, ep_1_states)]
    
    # Para este test, train y val serán el mismo episodio
    # Queremos ver si es capaz de calcarlo
    ds_train = EpisodeDataset(pairs, cfg['input_size'], stats)
    ds_val   = EpisodeDataset(pairs, cfg['input_size'], stats)

    dl_train = DataLoader(ds_train, batch_size=1, shuffle=False)
    dl_val   = DataLoader(ds_val, batch_size=1, shuffle=False)
    
    print(f"\n MODO TEST: Entrenando solo con {pairs[0][0]}")
    return dl_train, dl_val
"""

def run_epoch(model, loader, optimizer, criterion, cfg, device, train: bool):
    model.train(train)
    total_loss = 0.0
    batches = 0
    phase = "Train" if train else "Val  "

    pbar = tqdm(loader, desc=f"  {phase}", unit="batch", leave=False)

    with torch.set_grad_enabled(train):
        for b_events, b_torques in pbar:
            # Ahora la forma es (B, Tiempo_Total, C, H, W)
            B, T_total, C, H, W = b_events.shape
            state = model.init_state(batch_size=B, device=device)
            d_shift = CONFIG['d_shift'] 
            seq = cfg['seq_length']

            if train:
                optimizer.zero_grad()   # un solo zero_grad por episodio

            accumulated_chunks = []

            for start in range(0, T_total - d_shift, seq):
                end = min(start + seq, T_total - d_shift)
                if end - start < 10: break # Evitar ventanas muy pequeñas al final

                # 3. HEREDAMOS LA MEMORIA SIN ROMPER EL GRAFO COMPUTACIONAL
                state = {k: v.detach() for k, v in state.items()}
                loss_chunk = torch.tensor(0.0, device=device)

                for t in range(start, end):
                    x_t    = b_events[:, t].to(device)
                    target = b_torques[:, t + d_shift].to(device)
                    
                    if train and t > 0:
                        state['prev_torque'] = b_torques[:, t - 1 + d_shift].to(device).detach()
                    
                    pred_torque, state = model(x_t, state)

                    # Calculamos el error base
                    raw_loss = criterion(pred_torque, target)
                    
                    # Le damos hasta x3 de importancia a los torques grandes
                    weight = 1.0 + 50.0 * torch.abs(target)
                    
                    # Acumulamos el error ponderado en lugar del simple
                    loss_chunk = loss_chunk + torch.mean(raw_loss * weight)

                    #loss_chunk = loss_chunk + criterion(pred_torque, target)

                loss_chunk /= (end - start)
                accumulated_chunks.append(loss_chunk)

            if not accumulated_chunks:
                continue

            loss_episode = sum(accumulated_chunks) / len(accumulated_chunks)
                
                
            if train:
                loss_episode.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), cfg['grad_clip'])
                optimizer.step()
            
            # Promediamos el error de este bloque de episodios
            avg_loss = loss_episode.item()
            total_loss += avg_loss
            batches += 1
            pbar.set_postfix({'loss': f'{avg_loss:.4f}'})

    return total_loss / batches


def train():
    device = torch.device('mps')
    print(f"Device: {device}  (input_size: {CONFIG['input_size']}×{CONFIG['input_size']})")

    stats = load_stats(CONFIG['data_dir'])
    print(f"\nNormalisation stats loaded from {CONFIG['data_dir']}/dataset_stats.npz")
    print(f"  torque_std = {stats['torque_std']}")

    dl_train, dl_val = build_dataloaders(CONFIG, stats)

    model = SpikingSatelliteController(
        num_steps=CONFIG['num_steps'],
        hidden_gru=CONFIG['hidden_gru'],
        learn_beta=True,
    ).to(device)

    # --- CARGAR LOS PESOS ANTES DEL OPTIMIZADOR ---
    if CONFIG['re-train']:
        import shutil
        best_path = os.path.join(CONFIG['weights_dir'], 'best_model.pth')
        original_path = os.path.join(CONFIG['weights_dir'], 'original_model.pth')
        
        # 1. Proteger el modelo original: Si existe best_model pero no original_model, lo copiamos
        if os.path.exists(best_path) and not os.path.exists(original_path):
            shutil.copy(best_path, original_path)
            print(f"\n[INFO] Copia de seguridad creada: {original_path}")
            
        # 2. Elegir de dónde cargamos (priorizando siempre el original como base limpia)
        load_path = original_path if os.path.exists(original_path) else best_path
        
        if os.path.exists(load_path):
            print(f"\n[INFO] Reanudando entrenamiento (Fine-Tuning) desde: {load_path}")
            model.load_state_dict(torch.load(load_path, map_location=device))
        else:
            print("\n[INFO] No se encontró ningún modelo previo. Iniciando desde cero.")
    # -----------------------------------------------------

    optimizer = optim.AdamW(model.parameters(),
                            lr=CONFIG['lr'],
                            weight_decay=CONFIG['weight_decay'])
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=3
    )
    criterion = nn.MSELoss(reduction='none')
    #criterion = nn.SmoothL1Loss()

    os.makedirs(CONFIG['weights_dir'], exist_ok=True)
    best_val   = float('inf')
    no_improve = 0
    prev_lr    = CONFIG['lr']

    print(f"\nStarting training — {CONFIG['epochs']} epochs\n{'='*55}")

    for epoch in range(1, CONFIG['epochs'] + 1):
        tr_loss = run_epoch(model, dl_train, optimizer, criterion,
                                        CONFIG, device, train=True)
        vl_loss = run_epoch(model, dl_val,   optimizer, criterion,
                                        CONFIG, device, train=False)

        scheduler.step(vl_loss)

        current_lr = optimizer.param_groups[0]['lr']
        if current_lr < prev_lr:
            print(f"  → LR reducido a {current_lr:.2e}")
            prev_lr = current_lr

        flag = ''
        if vl_loss < best_val:
            best_val   = vl_loss
            no_improve = 0
            ckpt = os.path.join(CONFIG['weights_dir'], 'best_model.pth')
            torch.save(model.state_dict(), ckpt)
            flag = ' ← best'
        else:
            no_improve += 1

        print(f"Epoch {epoch:03d}/{CONFIG['epochs']} | "
              f"Train Loss: {tr_loss:.6f} | "
              f"Val Loss: {vl_loss:.6f}{flag}")

        if no_improve >= CONFIG['patience']:
            print(f"\nEarly stopping — no improvement for {CONFIG['patience']} epochs.")
            break

    print(f"\nTraining complete. Best val loss: {best_val:.4f}")
    print(f"Weights saved to: {CONFIG['weights_dir']}/best_model.pth")


if __name__ == '__main__':
    train()
